### PR TITLE
Fix render_partial in example code

### LINKED ISSUE #8: is render_partial working ?
salut !

I'm playing a little with this repo, after I spent too much time parsing htmx headers so I like the HTMXDetails class a lot now,

However, I started the example but it seems like instead of rendering html, `render_partial` is rendering a string of that html ...

see the screenshot for a better description

is there anything I'm doing incorrectly ?
20230529_0802_1063x319_1685340172

### PR DESCRIPTION
**Pull request by euri10**
fix #8

### CODE REVIEW

**Comment by euri10** [comment]
i could not bother to add test, one good way would be to extend existing ones, test for the 200 but also parse the generated html and see if we get partials, not sure it's worth the hassle

**Comment by euri10** [comment]
well it seems adding tests breaks coverage, locally it is at 100% so I dont get what codecov is trying to say here

**Comment by florimondmanca** [comment]
I just looked things up and it seems like we don’t run FastAPI or Quart tests on CI because there’s an importskip and they aren’t in requirements.txt. So expanding those tests mechanically reduces coverage because that’s more uncovered lines.

Maybe we should add FastAPI and Quart to requirements.txt? In the meantime I’m happy to merge this as-is.

**Review by florimondmanca — APPROVED** [review]
👍

**Pull request merged**
